#Site settings
title: LLDMqueens
email:
description:
url: 'http://lldmqueens.github.io'

# Build settings

markdown: kramdown
permalink: pretty

port: 3000

sass:
  sass_dir: assets/css
  style: :nested
